server:
  port: 8771
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://39.106.125.199:9411/
  
